In [2]:
from google.cloud import language
from google.cloud.language import enums
from google.cloud.language import types
import pandas as pd 

# Instantiates a client
client = language.LanguageServiceClient()

In [6]:
#import CSV
kanye = "no_period.csv"
kanye_df = pd.read_csv(kanye)
kanye_df.head()

,album,year_released,song,lyric
0,College Dropout,2004,Intro,"Kanye, can I talk to you for a minute? Me..."
1,College Dropout,2004,We Don't Care,And all my people thats drug dealin jus ...
2,College Dropout,2004,Graduation Day,What in the fuck was that Kanye I told yo...
3,College Dropout,2004,All Falls Down,"Oh when it all, it all falls down I'm t..."
4,College Dropout,2004,I'll Fly Away,"Some glad morning when this life is over, ..."

In [7]:
#create a new column to house sentiment score
kanye_df['sentiment'] = ''
kanye_df

,album,year_released,song,lyric,sentiment
0,College Dropout,2004,Intro,"Kanye, can I talk to you for a minute? Me...",
1,College Dropout,2004,We Don't Care,And all my people thats drug dealin jus ...,
2,College Dropout,2004,Graduation Day,What in the fuck was that Kanye I told yo...,
3,College Dropout,2004,All Falls Down,"Oh when it all, it all falls down I'm t...",
4,College Dropout,2004,I'll Fly Away,"Some glad morning when this life is over, ...",
...,...,...,...,...,...
126,Jesus is King,2019,Water,"Well, right So, so well Well, right So, so Hig...",
127,Jesus is King,2019,God Is,"God is My light in darkness, oh God, God is He...",
128,Jesus is King,2019,Hands On,"Hand 'em Hands up high, hands on, hands on Han...",
129,Jesus is King,2019,Use This Gospel,Use this Gospel for protection It's a hard roa...,
130,Jesus is King,2019,Jesus is Lord,Every knee shall bow Every tongue confess Jesu...,

In [10]:
for index,row in kanye_df.iterrows(): 
    text = (row["lyric"])
    document = types.Document(content=text,type=enums.Document.Type.PLAIN_TEXT)
    sentiment = client.analyze_sentiment(document=document).document_sentiment
    print((sentiment.score))

0.30000001192092896
-0.5
-0.699999988079071
-0.699999988079071
0.20000000298023224
-0.5
-0.30000001192092896
0.0
-0.5
0.0
0.10000000149011612
0.5
-0.20000000298023224
0.10000000149011612
0.10000000149011612
-0.20000000298023224
0.0
-0.10000000149011612
-0.20000000298023224
0.0
-0.4000000059604645
-0.10000000149011612
-0.10000000149011612
0.20000000298023224
-0.20000000298023224
-0.10000000149011612
0.0
-0.800000011920929
-0.10000000149011612
0.20000000298023224
-0.30000001192092896
-0.10000000149011612
-0.8999999761581421
-0.20000000298023224
0.20000000298023224
-0.20000000298023224
0.5
0.0
-0.5
0.0
-0.20000000298023224
-0.5
0.0
-0.10000000149011612
0.0
-0.4000000059604645
0.30000001192092896
0.0
0.0
-0.5
-0.20000000298023224
-0.30000001192092896
-0.4000000059604645
0.0
-0.699999988079071
-0.6000000238418579
-0.800000011920929
0.0
-0.699999988079071
-0.4000000059604645
-0.6000000238418579
0.8999999761581421
-0.5
-0.800000011920929
-0.30000001192092896
-0.30000001192092896
-0.20000000298023224
-0.10000000149011612
0.0
-0.10000000149011612
-0.20000000298023224
-0.20000000298023224
-0.20000000298023224
0.10000000149011612
-0.30000001192092896
-0.699999988079071
-0.10000000149011612
-0.800000011920929
0.0
0.0
-0.10000000149011612
-0.20000000298023224
0.10000000149011612
-0.6000000238418579
-0.5
-0.10000000149011612
-0.699999988079071
-0.800000011920929
-0.30000001192092896
-0.5
0.10000000149011612
-0.20000000298023224
0.0
-0.10000000149011612
0.10000000149011612
-0.30000001192092896
0.0
0.0
0.5
-0.10000000149011612
-0.30000001192092896
0.0
-0.20000000298023224
0.0
-0.10000000149011612
-0.30000001192092896
0.30000001192092896
0.4000000059604645
0.0
-0.20000000298023224
0.0
0.4000000059604645
0.0
-0.30000001192092896
-0.10000000149011612
-0.10000000149011612
-0.5
0.30000001192092896
-0.10000000149011612
0.0
0.20000000298023224
0.4000000059604645
0.4000000059604645
-0.20000000298023224
-0.10000000149011612
0.30000001192092896
0.30000001192092896
0.6000000238418579
-0.4000000059604645
0.4000000059604645
0.0